Meteor.startup(function () {
  if (Plans.find().count() === 0) {
    Plans.insert({chapterName: 'Creation & Fall',chapterNumber: 1,date: '1/1',readingShort: 'Gen 1-3',psalm: '1',rating: 0});
    Plans.insert({chapterName: 'Creation & Fall',chapterNumber: 1,date: '1/2',readingShort: 'Gen 4-7',psalm: '2',rating: 0});
    Plans.insert({chapterName: 'Creation & Fall',chapterNumber: 1,date: '1/3',readingShort: 'Gen 8-11',psalm: '3',rating: 0});
    Plans.insert({chapterName: 'The Covenant with Abraham',chapterNumber: 2,date: '1/4',readingShort: 'Gen 12-15',psalm: '4',rating: 0});
    Plans.insert({chapterName: 'The Covenant with Abraham',chapterNumber: 2,date: '1/5',readingShort: 'Gen 16-18',psalm: '5',rating: 0});
    Plans.insert({chapterName: 'The Covenant with Abraham',chapterNumber: 2,date: '1/6',readingShort: 'Gen 19-21',psalm: '6',rating: 0});
    Plans.insert({chapterName: 'The Covenant with Abraham',chapterNumber: 2,date: '1/7',readingShort: 'Gen 22-24',psalm: '7',rating: 0});
    Plans.insert({chapterName: 'The Covenant with Abraham',chapterNumber: 2,date: '1/8',readingShort: 'Gen 25-28',psalm: '8',rating: 0});
    Plans.insert({chapterName: 'The Covenant with Abraham',chapterNumber: 2,date: '1/9',readingShort: 'Gen 29-31',psalm: '9',rating: 0});
    Plans.insert({chapterName: 'The Covenant with Abraham',chapterNumber: 2,date: '1/10',readingShort: 'Gen 32-34',psalm: '10',rating: 0});
    Plans.insert({chapterName: 'The Covenant with Abraham',chapterNumber: 2,date: '1/11',readingShort: 'Gen 35-37',psalm: '11',rating: 0});
    Plans.insert({chapterName: 'The Covenant with Abraham',chapterNumber: 2,date: '1/12',readingShort: 'Gen 38-40',psalm: '12',rating: 0});
    Plans.insert({chapterName: 'The Covenant with Abraham',chapterNumber: 2,date: '1/13',readingShort: 'Gen 41-42',psalm: '13',rating: 0});
    Plans.insert({chapterName: 'The Covenant with Abraham',chapterNumber: 2,date: '1/14',readingShort: 'Gen 43-45',psalm: '14',rating: 0});
    Plans.insert({chapterName: 'The Covenant with Abraham',chapterNumber: 2,date: '1/15',readingShort: 'Gen 46-47',psalm: '15',rating: 0});
    Plans.insert({chapterName: 'The Covenant with Abraham',chapterNumber: 2,date: '1/16',readingShort: 'Gen 48-50',psalm: '16',rating: 0});
    Plans.insert({chapterName: 'The Exodus from Egypt',chapterNumber: 3,date: '1/17',readingShort: 'Ex 1-3',psalm: '17',rating: 0});
    Plans.insert({chapterName: 'The Exodus from Egypt',chapterNumber: 3,date: '1/18',readingShort: 'Ex 4-6',psalm: '18',rating: 0});
    Plans.insert({chapterName: 'The Exodus from Egypt',chapterNumber: 3,date: '1/19',readingShort: 'Ex 7-9',psalm: '19',rating: 0});
    Plans.insert({chapterName: 'The Exodus from Egypt',chapterNumber: 3,date: '1/20',readingShort: 'Ex 10-12',psalm: '20',rating: 0});
    Plans.insert({chapterName: 'The Exodus from Egypt',chapterNumber: 3,date: '1/21',readingShort: 'Ex 13-15',psalm: '21',rating: 0});
    Plans.insert({chapterName: 'The Exodus from Egypt',chapterNumber: 3,date: '1/22',readingShort: 'Ex 16-18',psalm: '22',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '1/23',readingShort: 'Ex 19-21',psalm: '23',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '1/24',readingShort: 'Ex 22-24',psalm: '24',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '1/25',readingShort: 'Ex 25-27',psalm: '25',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '1/26',readingShort: 'Ex 28-29',psalm: '26',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '1/27',readingShort: 'Ex 30-31',psalm: '27',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '1/28',readingShort: 'Ex 32-34',psalm: '28',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '1/29',readingShort: 'Ex 35-40',psalm: '29',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '1/30',readingShort: 'Lev 1-4',psalm: '30',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '1/31',readingShort: 'Lev 5-7',psalm: '31',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '2/1',readingShort: 'Lev 8-10',psalm: '32',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '2/2',readingShort: 'Lev 11-13',psalm: '33',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '2/3',readingShort: 'Lev 14-15',psalm: '34',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '2/4',readingShort: 'Lev 16-18',psalm: '35',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '2/5',readingShort: 'Lev 19-20',psalm: '36',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '2/6',readingShort: 'Lev 21-23',psalm: '37',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '2/7',readingShort: 'Lev 24-25',psalm: '38',rating: 0});
    Plans.insert({chapterName: 'The Covenant at Mount Sinai',chapterNumber: 4,date: '2/8',readingShort: 'Lev 26-27',psalm: '39',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/9',readingShort: 'Num 1-4',psalm: '40',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/10',readingShort: 'Num 5-7',psalm: '41',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/11',readingShort: 'Num 8-10',psalm: '42',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/12',readingShort: 'Num 11-13',psalm: '43',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/13',readingShort: 'Num 14-16',psalm: '44',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/14',readingShort: 'Num 17-18',psalm: '45',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/15',readingShort: 'Num 19-21',psalm: '46',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/16',readingShort: 'Num 22-24',psalm: '47',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/17',readingShort: 'Num 25-27',psalm: '48',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/18',readingShort: 'Num 28-30',psalm: '49',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/19',readingShort: 'Num 31-32',psalm: '50',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/20',readingShort: 'Num 33-34',psalm: '51',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/21',readingShort: 'Num 35-36',psalm: '52',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/22',readingShort: 'Deuteronomy 1-3',psalm: '53',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/23',readingShort: 'Deuteronomy 4-6',psalm: '54',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/24',readingShort: 'Deuteronomy 7-9',psalm: '55',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/25',readingShort: 'Deuteronomy 10-12',psalm: '56',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/26',readingShort: 'Deuteronomy 13-14',psalm: '57',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/27',readingShort: 'Deuteronomy 15-16',psalm: '58',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/28',readingShort: 'Deuteronomy 17-20',psalm: '59',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '2/29',readingShort: 'Deuteronomy 21-23',psalm: '60',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '3/1',readingShort: 'Deuteronomy 24-27',psalm: '61',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '3/2',readingShort: 'Deuteronomy 28-29',psalm: '62',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '3/3',readingShort: 'Deuteronomy 30-31',psalm: '63',rating: 0});
    Plans.insert({chapterName: 'The Wilderness',chapterNumber: 5,date: '3/4',readingShort: 'Deuteronomy 32-34',psalm: '64',rating: 0});
    Plans.insert({chapterName: 'The Promised Land',chapterNumber: 6,date: '3/5',readingShort: 'Josh 1-4',psalm: '65',rating: 0});
    Plans.insert({chapterName: 'The Promised Land',chapterNumber: 6,date: '3/6',readingShort: 'Josh 5-8',psalm: '66',rating: 0});
    Plans.insert({chapterName: 'The Promised Land',chapterNumber: 6,date: '3/7',readingShort: 'Josh 9-12',psalm: '67',rating: 0});
    Plans.insert({chapterName: 'The Promised Land',chapterNumber: 6,date: '3/8',readingShort: 'Josh 13-21',psalm: '68',rating: 0});
    Plans.insert({chapterName: 'The Promised Land',chapterNumber: 6,date: '3/9',readingShort: 'Josh 22-24',psalm: '69',rating: 0});
    Plans.insert({chapterName: 'The Promised Land',chapterNumber: 6,date: '3/10',readingShort: 'Jdgs 1-3',psalm: '70',rating: 0});
    Plans.insert({chapterName: 'The Promised Land',chapterNumber: 6,date: '3/11',readingShort: 'Jdgs 4-5',psalm: '71',rating: 0});
    Plans.insert({chapterName: 'The Promised Land',chapterNumber: 6,date: '3/12',readingShort: 'Jdgs 6-8',psalm: '72',rating: 0});
    Plans.insert({chapterName: 'The Promised Land',chapterNumber: 6,date: '3/13',readingShort: 'Jdgs 9-12',psalm: '73',rating: 0});
    Plans.insert({chapterName: 'The Promised Land',chapterNumber: 6,date: '3/14',readingShort: 'Jdgs 13-15',psalm: '74',rating: 0});
    Plans.insert({chapterName: 'The Promised Land',chapterNumber: 6,date: '3/15',readingShort: 'Jdgs 16-18',psalm: '75',rating: 0});
    Plans.insert({chapterName: 'The Promised Land',chapterNumber: 6,date: '3/16',readingShort: 'Jdgs 19-21',psalm: '76',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/17',readingShort: 'Ruth',psalm: '77',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/18',readingShort: '1 Sam 1-3',psalm: '78',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/19',readingShort: '1 Sam 4-8',psalm: '79',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/20',readingShort: '1 Sam 9-12',psalm: '80',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/21',readingShort: '1 Sam 13-14',psalm: '81',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/22',readingShort: '1 Sam 15-17',psalm: '82',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/23',readingShort: '1 Sam 18-20',psalm: '83',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/24',readingShort: '1 Sam 21-24',psalm: '84',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/25',readingShort: '1 Sam 25-27',psalm: '85',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/26',readingShort: '1 Sam 28-31',psalm: '86',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/27',readingShort: '2 Sam 1-3',psalm: '87',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/28',readingShort: '2 Sam 4-8',psalm: '88',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/29',readingShort: '2 Sam 9-12',psalm: '89',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/30',readingShort: '2 Sam 13-15',psalm: '90',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '3/31',readingShort: '2 Sam 16-18',psalm: '91',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/1',readingShort: '2 Sam 19-21',psalm: '92',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/2',readingShort: '2 Sam 22-24',psalm: '93',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/3',readingShort: '1 Kings 1-3',psalm: '94',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/4',readingShort: '1 Kings 4-7',psalm: '95',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/5',readingShort: '1 Kings 8-10',psalm: '96',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/6',readingShort: '1 Kings 11-13',psalm: '97',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/7',readingShort: '1 Kings 14-16',psalm: '98',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/8',readingShort: '1 Kings 17-19',psalm: '99',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/9',readingShort: '1 Kings 20-22',psalm: '100',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/10',readingShort: '2 Kings 1-3',psalm: '101',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/11',readingShort: '2 Kings 4-7',psalm: '102',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/12',readingShort: '2 Kings 8-11',psalm: '103',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/13',readingShort: '2 Kings 12-14',psalm: '104',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/14',readingShort: '2 Kings 15-17',psalm: '105',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/15',readingShort: '2 Kings 18-19',psalm: '106',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/16',readingShort: '2 Kings 20-22',psalm: '107',rating: 0});
    Plans.insert({chapterName: 'Rise & Fall of Israel\'s Kingdom',chapterNumber: 7,date: '4/17',readingShort: '2 Kings 23-25',psalm: '108',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '4/18',readingShort: 'Isa 1-4',psalm: '109',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '4/19',readingShort: 'Isa 5-8',psalm: '110',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '4/20',readingShort: 'Isa 9-12',psalm: '111',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '4/21',readingShort: 'Isa 13-17',psalm: '112',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '4/22',readingShort: 'Isa 18-22',psalm: '113',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '4/23',readingShort: 'Isa 23-27',psalm: '114',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '4/24',readingShort: 'Isa 28-30',psalm: '115',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '4/25',readingShort: 'Isa 31-35',psalm: '116',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '4/26',readingShort: 'Isa 36-38',psalm: '117',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '4/27',readingShort: 'Isa 39-41',psalm: '118',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '4/28',readingShort: 'Isa 42-44',psalm: '119:1-32',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '4/29',readingShort: 'Isa 45-48',psalm: '119:33-64',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '4/30',readingShort: 'Isa 49-51',psalm: '119:65-96',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/1',readingShort: 'Isa 52-54',psalm: '119:97-128',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/2',readingShort: 'Isa 55-57',psalm: '119:129-152',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/3',readingShort: 'Isa 58-60',psalm: '119:153-176',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/4',readingShort: 'Isa 61-64',psalm: '120',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/5',readingShort: 'Isa 65-66',psalm: '121',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/6',readingShort: 'Hos 1-5',psalm: '122',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/7',readingShort: 'Hos 6-10',psalm: '123',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/8',readingShort: 'Hos 11-14',psalm: '124',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/9',readingShort: 'Joel',psalm: '125',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/10',readingShort: 'Amos 1-5',psalm: '126',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/11',readingShort: 'Amos 6-9',psalm: '127',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/12',readingShort: 'Obadiah',psalm: '128',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/13',readingShort: 'Jonah',psalm: '129',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/14',readingShort: 'Micah 1-4',psalm: '130',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/15',readingShort: 'Micah 5-7',psalm: '131',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/16',readingShort: 'Nahum',psalm: '132',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/17',readingShort: 'Habakkuk',psalm: '133',rating: 0});
    Plans.insert({chapterName: 'The Prophets Before the Exile',chapterNumber: 8,date: '5/18',readingShort: 'Zephaniah',psalm: '134',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '5/19',readingShort: 'Job 1-3',psalm: '135',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '5/20',readingShort: 'Job 4-7',psalm: '136',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '5/21',readingShort: 'Job 8-11',psalm: '137',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '5/22',readingShort: 'Job 12-15',psalm: '138',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '5/23',readingShort: 'Job 16-19',psalm: '139',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '5/24',readingShort: 'Job 20-23',psalm: '140',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '5/25',readingShort: 'Job 24-28',psalm: '141',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '5/26',readingShort: 'Job 29-31',psalm: '142',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '5/27',readingShort: 'Job 32-34',psalm: '143',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '5/28',readingShort: 'Job 35-37',psalm: '144',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '5/29',readingShort: 'Job 38-39',psalm: '145',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '5/30',readingShort: 'Job 40-42',psalm: '146',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '5/31',readingShort: 'Psalm 1-2',psalm: '147',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/1',readingShort: 'Prov 1-3',psalm: '148',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/2',readingShort: 'Prov 4-6',psalm: '149',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/3',readingShort: 'Prov 7-9',psalm: '150',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/4',readingShort: 'Prov 10-12',psalm: '1',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/5',readingShort: 'Prov 13-15',psalm: '2',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/6',readingShort: 'Prov 16-18',psalm: '3',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/7',readingShort: 'Prov 19-21',psalm: '4',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/8',readingShort: 'Prov 22-24',psalm: '5',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/9',readingShort: 'Prov 25-27',psalm: '6',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/10',readingShort: 'Prov 28-31',psalm: '7',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/11',readingShort: 'Ecc 1-4',psalm: '8',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/12',readingShort: 'Ecc 5-8',psalm: '9',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/13',readingShort: 'Ecc 9-12',psalm: '10',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/14',readingShort: 'Song 1-4',psalm: '11',rating: 0});
    Plans.insert({chapterName: 'The Wisdom of Israel',chapterNumber: 9,date: '6/15',readingShort: 'Song 5-8',psalm: '12',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/16',readingShort: 'Jer 1-3',psalm: '13',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/17',readingShort: 'Jer 4-6',psalm: '14',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/18',readingShort: 'Jer 7-9',psalm: '15',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/19',readingShort: 'Jer 10-13',psalm: '16',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/20',readingShort: 'Jer 14-17',psalm: '17',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/21',readingShort: 'Jer 18-22',psalm: '18',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/22',readingShort: 'Jer 23-25',psalm: '19',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/23',readingShort: 'Jer 26-29',psalm: '20',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/24',readingShort: 'Jer 30-32',psalm: '21',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/25',readingShort: 'Jer 33-36',psalm: '22',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/26',readingShort: 'Jer 37-39',psalm: '23',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/27',readingShort: 'Jer 40-44',psalm: '24',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/28',readingShort: 'Jer 45-48',psalm: '25',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/29',readingShort: 'Jer 49-50',psalm: '26',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '6/30',readingShort: 'Jer 51-52',psalm: '27',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/1',readingShort: 'Lam 1-2',psalm: '28',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/2',readingShort: 'Lam 3',psalm: '29',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/3',readingShort: 'Lam 4-5',psalm: '30',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/4',readingShort: 'Ezk 1-4',psalm: '31',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/5',readingShort: 'Ezk 5-8',psalm: '32',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/6',readingShort: 'Ezk 9-12',psalm: '33',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/7',readingShort: 'Ezk 13-15',psalm: '34',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/8',readingShort: 'Ezk 16-18',psalm: '35',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/9',readingShort: 'Ezk 19-21',psalm: '36',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/10',readingShort: 'Ezk 22-24',psalm: '37',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/11',readingShort: 'Ezk 25-27',psalm: '38',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/12',readingShort: 'Ezk 28-30',psalm: '39',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/13',readingShort: 'Ezk 31-33',psalm: '40',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/14',readingShort: 'Ezk 34-36',psalm: '41',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/15',readingShort: 'Ezk 37-39',psalm: '42',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/16',readingShort: 'Ezk 40-44',psalm: '43',rating: 0});
    Plans.insert({chapterName: 'The Prophets of the Exile',chapterNumber: 10,date: '7/17',readingShort: 'Ezk 45-48',psalm: '44',rating: 0});
    Plans.insert({chapterName: 'The Return from Exile',chapterNumber: 11,date: '7/18',readingShort: 'Ezra 1-3',psalm: '45',rating: 0});
    Plans.insert({chapterName: 'The Return from Exile',chapterNumber: 11,date: '7/19',readingShort: 'Ezra 4-7',psalm: '46',rating: 0});
    Plans.insert({chapterName: 'The Return from Exile',chapterNumber: 11,date: '7/20',readingShort: 'Ezra 8-10',psalm: '47',rating: 0});
    Plans.insert({chapterName: 'The Return from Exile',chapterNumber: 11,date: '7/21',readingShort: 'Neh 1-3',psalm: '48',rating: 0});
    Plans.insert({chapterName: 'The Return from Exile',chapterNumber: 11,date: '7/22',readingShort: 'Neh 4-6',psalm: '49',rating: 0});
    Plans.insert({chapterName: 'The Return from Exile',chapterNumber: 11,date: '7/23',readingShort: 'Neh 7-9',psalm: '50',rating: 0});
    Plans.insert({chapterName: 'The Return from Exile',chapterNumber: 11,date: '7/24',readingShort: 'Neh 10-11',psalm: '51',rating: 0});
    Plans.insert({chapterName: 'The Return from Exile',chapterNumber: 11,date: '7/25',readingShort: 'Neh 12-13',psalm: '52',rating: 0});
    Plans.insert({chapterName: 'The Return from Exile',chapterNumber: 11,date: '7/26',readingShort: 'Esth 1-5',psalm: '53',rating: 0});
    Plans.insert({chapterName: 'The Return from Exile',chapterNumber: 11,date: '7/27',readingShort: 'Esth 6-10',psalm: '54',rating: 0});
    Plans.insert({chapterName: 'Prophets after the Exile',chapterNumber: 12,date: '7/28',readingShort: 'Dan 1-3',psalm: '55',rating: 0});
    Plans.insert({chapterName: 'Prophets after the Exile',chapterNumber: 12,date: '7/29',readingShort: 'Dan 4-6',psalm: '56',rating: 0});
    Plans.insert({chapterName: 'Prophets after the Exile',chapterNumber: 12,date: '7/30',readingShort: 'Dan 7-9',psalm: '57',rating: 0});
    Plans.insert({chapterName: 'Prophets after the Exile',chapterNumber: 12,date: '7/31',readingShort: 'Dan 10-12',psalm: '58',rating: 0});
    Plans.insert({chapterName: 'Prophets after the Exile',chapterNumber: 12,date: '8/1',readingShort: 'Haggai',psalm: '59',rating: 0});
    Plans.insert({chapterName: 'Prophets after the Exile',chapterNumber: 12,date: '8/2',readingShort: 'Zech 1-4',psalm: '60',rating: 0});
    Plans.insert({chapterName: 'Prophets after the Exile',chapterNumber: 12,date: '8/3',readingShort: 'Zech 5-8',psalm: '61',rating: 0});
    Plans.insert({chapterName: 'Prophets after the Exile',chapterNumber: 12,date: '8/4',readingShort: 'Zech 9-14',psalm: '62',rating: 0});
    Plans.insert({chapterName: 'Prophets after the Exile',chapterNumber: 12,date: '8/5',readingShort: 'Mal 1-2',psalm: '63',rating: 0});
    Plans.insert({chapterName: 'Prophets after the Exile',chapterNumber: 12,date: '8/6',readingShort: 'Mal 3-4',psalm: '64',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/7',readingShort: '1Chr1-9',psalm: '65',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/8',readingShort: '1 Chr 11-14',psalm: '66',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/9',readingShort: '1 Chr 15-17',psalm: '67',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/10',readingShort: '1 Chr 18-21',psalm: '68',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/11',readingShort: '1 Chr 22-24',psalm: '69',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/12',readingShort: '1 Chr 25-28',psalm: '70',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/13',readingShort: '2 Chr 1-4',psalm: '71',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/14',readingShort: '2 Chr 5-8',psalm: '72',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/15',readingShort: '2 Chr 9-12',psalm: '73',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/16',readingShort: '2 Chr 13-17',psalm: '74',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/17',readingShort: '2 Chr 18-20',psalm: '75',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/18',readingShort: '2 Chr 21-24',psalm: '76',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/19',readingShort: '2 Chr 25-27',psalm: '77',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/20',readingShort: '2 Chr 28-31',psalm: '78',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/21',readingShort: '2 Chr 32-34',psalm: '79',rating: 0});
    Plans.insert({chapterName: 'The Story so Far',chapterNumber: 13,date: '8/22',readingShort: '2 Chr 35-36',psalm: '80',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '8/23',readingShort: 'Matt 1-2',psalm: '81',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '8/24',readingShort: 'Matt 3-4',psalm: '82',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '8/25',readingShort: 'Matt 5-6',psalm: '83',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '8/26',readingShort: 'Matt 7-8',psalm: '84',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '8/27',readingShort: 'Matt 9-10',psalm: '85',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '8/28',readingShort: 'Matt 11-12',psalm: '86',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '8/29',readingShort: 'Matt 13-14',psalm: '87',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '8/30',readingShort: 'Matt 15-16',psalm: '88',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '8/31',readingShort: 'Matt 17-18',psalm: '89',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/1',readingShort: 'Matt 19-20',psalm: '90',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/2',readingShort: 'Matt 21-22',psalm: '91',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/3',readingShort: 'Matt 23-24',psalm: '92',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/4',readingShort: 'Matt 25-26',psalm: '93',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/5',readingShort: 'Matt 27-28',psalm: '94',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/6',readingShort: 'Mark 1-2',psalm: '95',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/7',readingShort: 'Mark 3-4',psalm: '96',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/8',readingShort: 'Mark 5-6',psalm: '97',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/9',readingShort: 'Mark 7-8',psalm: '98',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/10',readingShort: 'Mark 9-10',psalm: '99',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/11',readingShort: 'Mark 11-12',psalm: '100',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/12',readingShort: 'Mark 13-14',psalm: '101',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/13',readingShort: 'Mark 15-16',psalm: '102',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/14',readingShort: 'John 1-2',psalm: '103',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/15',readingShort: 'John 3-4',psalm: '104',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/16',readingShort: 'John 5-6',psalm: '105',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/17',readingShort: 'John 7-8',psalm: '106',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/18',readingShort: 'John 9-10',psalm: '107',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/19',readingShort: 'John 11-12',psalm: '108',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/20',readingShort: 'John 13-15',psalm: '109',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/21',readingShort: 'John 16-18',psalm: '110',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/22',readingShort: 'John 19-21',psalm: '111',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/23',readingShort: 'Luke 1',psalm: '112',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/24',readingShort: 'Luke 2-3',psalm: '113',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/25',readingShort: 'Luke 4-5',psalm: '114',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/26',readingShort: 'Luke 6-7',psalm: '115',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/27',readingShort: 'Luke 8-9',psalm: '116',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/28',readingShort: 'Luke 10-11',psalm: '117',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/29',readingShort: 'Luke 12-13',psalm: '118',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '9/30',readingShort: 'Luke 14-16',psalm: '119:1-32',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/1',readingShort: 'Luke 17-18',psalm: '119:33-64',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/2',readingShort: 'Luke 19-20',psalm: '119:65-96',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/3',readingShort: 'Luke 21-22',psalm: '119:97-128',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/4',readingShort: 'Luke 23-24',psalm: '119:129-152',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/5',readingShort: 'Acts 1-2',psalm: '119:153-176',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/6',readingShort: 'Acts 3-4',psalm: '120',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/7',readingShort: 'Acts 5-6',psalm: '121',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/8',readingShort: 'Acts 7-8',psalm: '122',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/9',readingShort: 'Acts 9-10',psalm: '123',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/10',readingShort: 'Acts 11-12',psalm: '124',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/11',readingShort: 'Acts 13-14',psalm: '125',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/12',readingShort: 'Acts 15-16',psalm: '126',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/13',readingShort: 'Acts 17-18',psalm: '127',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/14',readingShort: 'Acts 19-20',psalm: '128',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/15',readingShort: 'Acts 21-22',psalm: '129',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/16',readingShort: 'Acts 23-24',psalm: '130',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/17',readingShort: 'Acts 25-26',psalm: '131',rating: 0});
    Plans.insert({chapterName: 'Jesus and the Kingdom',chapterNumber: 14,date: '10/18',readingShort: 'Acts 27-28',psalm: '132',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '10/19',readingShort: 'Rom 1-2',psalm: '133',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '10/20',readingShort: 'Rom 3-4',psalm: '134',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '10/21',readingShort: 'Rom 5-6',psalm: '135',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '10/22',readingShort: 'Rom 7-8',psalm: '136',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '10/23',readingShort: 'Rom 9-10',psalm: '137',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '10/24',readingShort: 'Rom 11-12',psalm: '138',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '10/25',readingShort: 'Rom 13-14',psalm: '139',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '10/26',readingShort: 'Rom 15-16',psalm: '140',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '10/27',readingShort: '1 Cor 1-2',psalm: '141',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '10/28',readingShort: '1 Cor 3-4',psalm: '142',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '10/29',readingShort: '1 Cor 5-6',psalm: '143',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '10/30',readingShort: '1 Cor 7-8',psalm: '144',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '10/31',readingShort: '1 Cor 9-10',psalm: '145',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/1',readingShort: '1 Cor 11-12',psalm: '146',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/2',readingShort: '1 Cor 13-14',psalm: '147',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/3',readingShort: '1 Cor 15-16',psalm: '148',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/4',readingShort: '2 Cor 1-2',psalm: '149',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/5',readingShort: '2 Cor 3-4',psalm: '150',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/6',readingShort: '2 Cor 5-6',psalm: '1',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/7',readingShort: '2 Cor 7-8',psalm: '2',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/8',readingShort: '2 Cor 9-10',psalm: '3',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/9',readingShort: '2 Cor 11-13',psalm: '4',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/10',readingShort: 'Gal 1-2',psalm: '5',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/11',readingShort: 'Gal 3-4',psalm: '6',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/12',readingShort: 'Gal 5-6',psalm: '7',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/13',readingShort: 'Eph 1-2',psalm: '8',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/14',readingShort: 'Eph 3-4',psalm: '9',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/15',readingShort: 'Eph 5-6',psalm: '10',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/16',readingShort: 'Phil 1-2',psalm: '11',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/17',readingShort: 'Phil 3-4',psalm: '12',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/18',readingShort: 'Col 1-2',psalm: '13',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/19',readingShort: 'Col 3-4',psalm: '14',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/20',readingShort: '1 Thess 1-2',psalm: '15',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/21',readingShort: '1 Thess 3-4',psalm: '16',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/22',readingShort: '1 Thess 5',psalm: '17',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/23',readingShort: '2 Thess',psalm: '18',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/24',readingShort: '1 Tim 1-2',psalm: '19',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/25',readingShort: '1 Tim 3-4',psalm: '20',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/26',readingShort: '1 Tim 5-6',psalm: '21',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/27',readingShort: '2 Tim 1-4',psalm: '22',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/28',readingShort: 'Titus',psalm: '23',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/29',readingShort: 'Philemon',psalm: '24',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '11/30',readingShort: 'Heb 1-2',psalm: '25',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '12/1',readingShort: 'Heb 3-4',psalm: '26',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '12/2',readingShort: 'Heb 5-6',psalm: '27',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '12/3',readingShort: 'Heb 7-8',psalm: '28',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '12/4',readingShort: 'Heb 9-10',psalm: '29',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '12/5',readingShort: 'Heb 11-13',psalm: '30',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '12/6',readingShort: 'James 1-3',psalm: '31',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '12/7',readingShort: 'James 4-5',psalm: '32',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '12/8',readingShort: '1 Peter 1-2',psalm: '33',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '12/9',readingShort: '1 Peter 3-5',psalm: '34',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '12/10',readingShort: '2 Peter',psalm: '35',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '12/11',readingShort: '1 John 1-2',psalm: '36',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '12/12',readingShort: '1 John 3-4',psalm: '37',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '12/13',readingShort: '1John 5, 2-3Jn',psalm: '38',rating: 0});
    Plans.insert({chapterName: 'The People of the Kingdom',chapterNumber: 15,date: '12/14',readingShort: 'Jude',psalm: '39',rating: 0});
    Plans.insert({chapterName: 'The Revelation',chapterNumber: 16,date: '12/15',readingShort: 'Rev 1-3',psalm: '40',rating: 0});
    Plans.insert({chapterName: 'The Revelation',chapterNumber: 16,date: '12/16',readingShort: 'Rev 4-6',psalm: '41',rating: 0});
    Plans.insert({chapterName: 'The Revelation',chapterNumber: 16,date: '12/17',readingShort: 'Rev 7-9',psalm: '42',rating: 0});
    Plans.insert({chapterName: 'The Revelation',chapterNumber: 16,date: '12/18',readingShort: 'Rev 10-11',psalm: '43',rating: 0});
    Plans.insert({chapterName: 'The Revelation',chapterNumber: 16,date: '12/19',readingShort: 'Rev 12-13',psalm: '44',rating: 0});
    Plans.insert({chapterName: 'The Revelation',chapterNumber: 16,date: '12/20',readingShort: 'Rev 14-16',psalm: '45',rating: 0});
    Plans.insert({chapterName: 'The Revelation',chapterNumber: 16,date: '12/21',readingShort: 'Rev 17-18',psalm: '46',rating: 0});
    Plans.insert({chapterName: 'The Revelation',chapterNumber: 16,date: '12/22',readingShort: 'Rev 19-20',psalm: '47',rating: 0});
    Plans.insert({chapterName: 'The Revelation',chapterNumber: 16,date: '12/23',readingShort: 'Rev 21-22',psalm: '48',rating: 0});
  }
});